# <font color=  #9370DB> **Proyecto Final Álgebra** </font>

##### <font color=#E6E6FA > **Sarah Beltrán 752069, Priscila Cervantes 750722, Mónica Ibarra 750601** </font>

## <font color=#d4b1e6  > **Exportación de datos** </font>

In [17]:
import pandas as pd 
import numpy as np
from numpy.linalg import inv
import time

In [18]:
data = pd.read_csv('matrizC.csv', sep=',')
data

,1,2,3,4,5,6,7,8,9,10,...,12,13,14,15,17,18,19,20,Unnamed: 19,Unnamed: 20
0,45661042,283,227,1820316,217161071,-,-,-,10,-,...,-,-,317,-,983,6119,1584,-,264652025,34466216
1,86276,7971250,3985328,12691033,280861277,-,7029,-,657,-,...,4271,-,4116,10,605,113953,593,-,305948632,183711064
2,4931145,3089478,33539349,3094215,49113854,14935672,4275842,209809,2101890,961559,...,2235677,69172,959354,2555727,643320,9781982,3196193,7547589,153377834,839214
3,923712,353383,579321,62592496,6448286,510917,1050488,12656,73406,510362,...,64449,293482,231582,1108787,28859,853486,93548,1607285,81062392,0
4,64290386,39284704,59910263,259846358,1566199154,112557714,117065838,4652312,26734290,6214222,...,37338473,1199565,18938931,6582785,3588960,20651187,34761552,20745267,2454081102,1335164706
5,22587553,12130118,20023361,65355295,286675302,28747650,33475782,1189923,6765024,1815393,...,10283343,291043,4517652,2196342,975872,6116306,8300783,5804204,531796555,171043949
6,8656254,6155767,9498466,23639085,103806216,9589520,21983642,500936,7333631,1751793,...,5391401,761736,2258451,1276366,418633,2706197,3288322,4879213,219764805,58273598
7,13898,20545,24709,144136,342000,3321737,1459940,48089,22215,2299929,...,210276,31986,39055,252586,48521,49724,34960,2531384,11196636,0
8,1385547,1242217,942115,5862350,23449654,20294570,6347599,530872,21854230,7549004,...,10946276,1526962,4173957,8081111,1042380,4944201,5867040,7826681,144249751,7501983
9,5241326,14635281,4266290,7602933,22948996,43849141,24144486,245288,6422970,39189297,...,1772776,3175483,1010079,716089,403627,4950077,1982688,8527212,196027442,12574759
10,1030466,9749663,1109374,13176425,43315225,46190181,15047219,1294193,12039452,10191016,...,13682392,1103736,3641681,5418057,1343101,9890603,6166833,5407725,214151055,13988
11,5572230,4104100,3159431,18910959,55752750,76340150,16400335,650863,9475353,23389599,...,15713162,8187232,7712177,7476409,1076497,3927081,3843277,11867793,280721289,1351831
12,-,5191917,-,101263,15636558,581681,266752,-,18627991,45475,...,-,888523,1024,-,-,-,1656,-,41358042,0
13,5900,1875404,2691184,8461440,53308191,10510634,16613327,765885,7606651,24242286,...,9730947,516792,5640691,4995270,1829179,9098006,2937208,12472618,197293072,3517228
14,-,-,107579,5720,3866,-,275583,2023,16681,815062,...,212008,-,-,607911,8631,393,21,3724631,6017786,0
15,-,-,-,424,12118,-,6156,15,299022,16,...,2241,30,2293,57117,12370,23083,409,1103931,1523589,0
16,39658,1107602,659950,2837940,12620499,77429,4668378,86658,398578,1390741,...,2005404,955714,935229,890734,82128,134386,247540,5127096,35463257,0
17,1401338,2795361,2367770,5130771,19960683,6478071,15345612,418613,2094827,3035222,...,2112206,219507,471456,867186,601253,2683878,369196,5768658,75332237,4746883
18,239,31,1277835,30524,137,-,3222025,19134,-,1199264,...,-,-,-,-,-,-,3086,-,5758817,0

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   1            19 non-null     object
 1   2            19 non-null     object
 2   3            19 non-null     object
 3   4            19 non-null     int64
 4   5            19 non-null     int64
 5   6            19 non-null     object
 6   7            19 non-null     object
 7   8            19 non-null     object
 8   9            19 non-null     object
 9   10           19 non-null     object
 10  11           19 non-null     object
 11  12           19 non-null     object
 12  13           19 non-null     object
 13  14           19 non-null     object
 14  15           19 non-null     object
 15  17           19 non-null     object
 16  18           19 non-null     object
 17  19           19 non-null     int64
 18  20           19 non-null     object
 19  Unnamed: 19  19 non-null     int64
 20  Unnamed: 20  19 non-null     int64
dtypes: int64(5), object(16)
memory usage: 3.2+ KB

In [20]:
# matriz de coeficientes C
C = data.iloc[:19,:19]
C=C.apply(pd.to_numeric, errors='coerce')
C

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20
0,45661042.0,283.0,227.0,1820316,217161071,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,317.0,NaN,983.0,6119.0,1584,NaN
1,86276.0,7971250.0,3985328.0,12691033,280861277,NaN,7029.0,NaN,657.0,NaN,222023.0,4271.0,NaN,4116.0,10.0,605.0,113953.0,593,NaN
2,4931145.0,3089478.0,33539349.0,3094215,49113854,14935672.0,4275842.0,209809.0,2101890.0,961559.0,6694012.0,2235677.0,69172.0,959354.0,2555727.0,643320.0,9781982.0,3196193,7547589.0
3,923712.0,353383.0,579321.0,62592496,6448286,510917.0,1050488.0,12656.0,73406.0,510362.0,3303577.0,64449.0,293482.0,231582.0,1108787.0,28859.0,853486.0,93548,1607285.0
4,64290386.0,39284704.0,59910263.0,259846358,1566199154,112557714.0,117065838.0,4652312.0,26734290.0,6214222.0,20706123.0,37338473.0,1199565.0,18938931.0,6582785.0,3588960.0,20651187.0,34761552,20745267.0
5,22587553.0,12130118.0,20023361.0,65355295,286675302,28747650.0,33475782.0,1189923.0,6765024.0,1815393.0,5796449.0,10283343.0,291043.0,4517652.0,2196342.0,975872.0,6116306.0,8300783,5804204.0
6,8656254.0,6155767.0,9498466.0,23639085,103806216,9589520.0,21983642.0,500936.0,7333631.0,1751793.0,2789805.0,5391401.0,761736.0,2258451.0,1276366.0,418633.0,2706197.0,3288322,4879213.0
7,13898.0,20545.0,24709.0,144136,342000,3321737.0,1459940.0,48089.0,22215.0,2299929.0,183861.0,210276.0,31986.0,39055.0,252586.0,48521.0,49724.0,34960,2531384.0
8,1385547.0,1242217.0,942115.0,5862350,23449654,20294570.0,6347599.0,530872.0,21854230.0,7549004.0,7817394.0,10946276.0,1526962.0,4173957.0,8081111.0,1042380.0,4944201.0,5867040,7826681.0
9,5241326.0,14635281.0,4266290.0,7602933,22948996,43849141.0,24144486.0,245288.0,6422970.0,39189297.0,3720325.0,1772776.0,3175483.0,1010079.0,716089.0,403627.0,4950077.0,1982688,8527212.0
10,1030466.0,9749663.0,1109374.0,13176425,43315225,46190181.0,15047219.0,1294193.0,12039452.0,10191016.0,9682073.0,13682392.0,1103736.0,3641681.0,5418057.0,1343101.0,9890603.0,6166833,5407725.0
11,5572230.0,4104100.0,3159431.0,18910959,55752750,76340150.0,16400335.0,650863.0,9475353.0,23389599.0,4294527.0,15713162.0,8187232.0,7712177.0,7476409.0,1076497.0,3927081.0,3843277,11867793.0
12,NaN,5191917.0,NaN,101263,15636558,581681.0,266752.0,NaN,18627991.0,45475.0,15202.0,NaN,888523.0,1024.0,NaN,NaN,NaN,1656,NaN
13,5900.0,1875404.0,2691184.0,8461440,53308191,10510634.0,16613327.0,765885.0,7606651.0,24242286.0,15418153.0,9730947.0,516792.0,5640691.0,4995270.0,1829179.0,9098006.0,2937208,12472618.0
14,NaN,NaN,107579.0,5720,3866,NaN,275583.0,2023.0,16681.0,815062.0,1815.0,212008.0,NaN,NaN,607911.0,8631.0,393.0,21,3724631.0
15,NaN,NaN,NaN,424,12118,NaN,6156.0,15.0,299022.0,16.0,3085.0,2241.0,30.0,2293.0,57117.0,12370.0,23083.0,409,1103931.0
16,39658.0,1107602.0,659950.0,2837940,12620499,77429.0,4668378.0,86658.0,398578.0,1390741.0,304245.0,2005404.0,955714.0,935229.0,890734.0,82128.0,134386.0,247540,5127096.0
17,1401338.0,2795361.0,2367770.0,5130771,19960683,6478071.0,15345612.0,418613.0,2094827.0,3035222.0,1419646.0,2112206.0,219507.0,471456.0,867186.0,601253.0,2683878.0,369196,5768658.0
18,239.0,31.0,1277835.0,30524,137,NaN,3222025.0,19134.0,NaN,1199264.0,6542.0,NaN,NaN,NaN,NaN,NaN,NaN,3086,NaN

In [21]:
# total producciones
total_p = data.iloc[:19,19:20]
total_p = total_p.apply(pd.to_numeric, errors='coerce')
total_p

    Unnamed: 19
0     264652025
1     305948632
2     153377834
3      81062392
4    2454081102
5     531796555
6     219764805
7      11196636
8     144249751
9     196027442
10    214151055
11    280721289
12     41358042
13    197293072
14      6017786
15      1523589
16     35463257
17     75332237
18      5758817

In [22]:
total_p = total_p.squeeze()

In [23]:
# vector de demanda final d
vector_d = data.iloc[:19,20:21]
vector_d

    Unnamed: 20
0      34466216
1     183711064
2        839214
3             0
4    1335164706
5     171043949
6      58273598
7             0
8       7501983
9      12574759
10        13988
11      1351831
12            0
13      3517228
14            0
15            0
16            0
17      4746883
18            0

## <font color=#d4b1e6  > **Visualización Matriz** </font>

In [24]:
print("Forma de C:", C.shape)
print("Forma de total_p:", total_p.shape)

Forma de C: (19, 19)
Forma de total_p: (19,)

In [25]:
C_final = C.div(total_p, axis=0)
C_final = C_final.fillna(0)
C_final

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20
0,0.172532,0.000001,8.577301e-07,0.006878,0.820553,0.000000,0.000000,0.000000,3.778547e-08,0.000000,0.000000,0.000000,0.000000,0.000001,0.000000e+00,0.000004,0.000023,0.000006,0.000000
1,0.000282,0.026054,1.302613e-02,0.041481,0.918001,0.000000,0.000023,0.000000,2.147419e-06,0.000000,0.000726,0.000014,0.000000,0.000013,3.268523e-08,0.000002,0.000372,0.000002,0.000000
2,0.032150,0.020143,2.186714e-01,0.020174,0.320215,0.097378,0.027878,0.001368,1.370400e-02,0.006269,0.043644,0.014576,0.000451,0.006255,1.666295e-02,0.004194,0.063777,0.020839,0.049209
3,0.011395,0.004359,7.146606e-03,0.772152,0.079547,0.006303,0.012959,0.000156,9.055494e-04,0.006296,0.040754,0.000795,0.003620,0.002857,1.367819e-02,0.000356,0.010529,0.001154,0.019828
4,0.026197,0.016008,2.441250e-02,0.105883,0.638202,0.045866,0.047703,0.001896,1.089381e-02,0.002532,0.008437,0.015215,0.000489,0.007717,2.682383e-03,0.001462,0.008415,0.014165,0.008453
5,0.042474,0.022810,3.765230e-02,0.122895,0.539069,0.054058,0.062948,0.002238,1.272108e-02,0.003414,0.010900,0.019337,0.000547,0.008495,4.130042e-03,0.001835,0.011501,0.015609,0.010914
6,0.039389,0.028011,4.322105e-02,0.107565,0.472351,0.043635,0.100033,0.002279,3.337036e-02,0.007971,0.012695,0.024533,0.003466,0.010277,5.807873e-03,0.001905,0.012314,0.014963,0.022202
7,0.001241,0.001835,2.206824e-03,0.012873,0.030545,0.296673,0.130391,0.004295,1.984078e-03,0.205413,0.016421,0.018780,0.002857,0.003488,2.255910e-02,0.004334,0.004441,0.003122,0.226084
8,0.009605,0.008612,6.531138e-03,0.040640,0.162563,0.140691,0.044004,0.003680,1.515027e-01,0.052333,0.054193,0.075884,0.010586,0.028936,5.602166e-02,0.007226,0.034275,0.040673,0.054258
9,0.026738,0.074659,2.176374e-02,0.038785,0.117070,0.223689,0.123169,0.001251,3.276567e-02,0.199917,0.018979,0.009044,0.016199,0.005153,3.653004e-03,0.002059,0.025252,0.010114,0.043500
10,0.004812,0.045527,5.180334e-03,0.061529,0.202265,0.215690,0.070265,0.006043,5.621944e-02,0.047588,0.045211,0.063891,0.005154,0.017005,2.530016e-02,0.006272,0.046185,0.028797,0.025252
11,0.019850,0.014620,1.125469e-02,0.067366,0.198605,0.271943,0.058422,0.002319,3.375360e-02,0.083320,0.015298,0.055974,0.029165,0.027473,2.663285e-02,0.003835,0.013989,0.013691,0.042276
12,0.000000,0.125536,0.000000e+00,0.002448,0.378078,0.014065,0.006450,0.000000,4.504080e-01,0.001100,0.000368,0.000000,0.021484,0.000025,0.000000e+00,0.000000,0.000000,0.000040,0.000000
13,0.000030,0.009506,1.364054e-02,0.042888,0.270198,0.053274,0.084206,0.003882,3.855508e-02,0.122874,0.078148,0.049322,0.002619,0.028590,2.531903e-02,0.009271,0.046114,0.014888,0.063219
14,0.000000,0.000000,1.787684e-02,0.000951,0.000642,0.000000,0.045795,0.000336,2.771950e-03,0.135442,0.000302,0.035230,0.000000,0.000000,1.010190e-01,0.001434,0.000065,0.000003,0.618937
15,0.000000,0.000000,0.000000e+00,0.000278,0.007954,0.000000,0.004040,0.000010,1.962616e-01,0.000011,0.002025,0.001471,0.000020,0.001505,3.748846e-02,0.008119,0.015150,0.000268,0.724560
16,0.001118,0.031232,1.860940e-02,0.080025,0.355875,0.002183,0.131640,0.002444,1.123918e-02,0.039216,0.008579,0.056549,0.026949,0.026372,2.511710e-02,0.002316,0.003789,0.006980,0.144575
17,0.018602,0.037107,3.143103e-02,0.068109,0.264969,0.085993,0.203706,0.005557,2.780784e-02,0.040291,0.018845,0.028039,0.002914,0.006258,1.151149e-02,0.007981,0.035627,0.004901,0.076576
18,0.000042,0.000005,2.218919e-01,0.005300,0.000024,0.000000,0.559494,0.003323,0.000000e+00,0.208248,0.001136,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000536,0.000000

In [26]:
I = np.eye(C_final.shape[0])  
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.]])

In [27]:
A = I - C_final
A = np.nan_to_num(A)

## <font color=#d4b1e6  > **Gauss-Jordan** </font>

In [28]:
def gauss_jordan(A, b):
    matriz = np.concatenate((A, b), axis=1)
    filas = matriz.shape[0]
    
    for i in range(filas):
        for j in range(i+1, filas):
            factor = -matriz[j, i] / matriz[i, i]
            matriz[j, :] = matriz[i, :] * factor + matriz[j, :]
            
    for i in range(filas-1, -1, -1):
        for j in range(i-1, -1, -1):
            factor = -matriz[j, i] / matriz[i, i]
            matriz[j, :] = matriz[i, :] * factor + matriz[j, :]
        
        matriz[i, :] = matriz[i, :] / matriz[i, i]
    
    x = matriz[:, -1]  # Última columna tiene las soluciones
    return x

In [29]:
tiempo_inicial = time.time()
x_gauss = gauss_jordan(A, vector_d.values)
tiempo_final = time.time()
tiempo_gauss = tiempo_final - tiempo_inicial

print("Solución con método de Gauss:", x_gauss)
print(f"Tiempo del método de Gauss: {tiempo_gauss:.6f} segundos")

Solución con método de Gauss: [4.99143328e+10 4.99405632e+10 4.74051459e+10 4.74266174e+10
 4.98933050e+10 4.84179262e+10 4.82903526e+10 4.76999987e+10
 4.71848214e+10 4.81993301e+10 4.73102312e+10 4.79141123e+10
 4.86116508e+10 4.62631705e+10 4.59804989e+10 4.77736988e+10
 4.74196074e+10 4.74259805e+10 4.80669753e+10]
Tiempo del método de Gauss: 0.004000 segundos

## <font color=#d4b1e6  > **Comprobación con función 'inv'** </font>

In [30]:
tiempo_inicial = time.time()
A_inv = np.linalg.inv(A)  
x_inv = np.dot(A_inv, vector_d.values)
tiempo_final = time.time()
print("Solución usando la inversa:", x_inv)
print(f"Tiempo de inversa: {tiempo_gauss:.6f} segundos")

Solución usando la inversa: [[4.99143328e+10]
 [4.99405632e+10]
 [4.74051459e+10]
 [4.74266174e+10]
 [4.98933050e+10]
 [4.84179262e+10]
 [4.82903526e+10]
 [4.76999987e+10]
 [4.71848214e+10]
 [4.81993301e+10]
 [4.73102312e+10]
 [4.79141123e+10]
 [4.86116508e+10]
 [4.62631705e+10]
 [4.59804989e+10]
 [4.77736988e+10]
 [4.74196074e+10]
 [4.74259805e+10]
 [4.80669753e+10]]
Tiempo de inversa: 0.004000 segundos

## <font color=#d4b1e6  > **Método de Gauss-Seidel** </font>

In [31]:
def gauss_seidel(A, b, tol=1**-20, max_iter=10000):
    n = len(b)
    x = np.zeros(n)  

    for k in range(max_iter):
        x_prev = np.copy(x)
        for i in range(n):
            sum_Ax_antes = sum(A[i][j] * x[j] for j in range(i))
            sum_Ax_desp = sum(A[i][j] * x_prev[j] for j in range(i + 1, n))
            x[i] = (b[i] - sum_Ax_antes - sum_Ax_desp) / A[i][i]
        
        norm_diff = np.linalg.norm(x - x_prev, ord=np.inf)
        norm_x = np.linalg.norm(x, ord=np.inf)
        
        if norm_diff / norm_x < tol:
            for idx, val in enumerate(x, 1):
                print(f'x{idx} = {val:.6f}')
            return x, k + 1

    print('No se puede calcular la solución')
    return None, max_iter

In [33]:
tiempo_inicial_gs = time.time()
x_g_s = gauss_seidel(A, vector_d.values)
tiempo_final_gs = time.time()
tiempo_gs = tiempo_final_gs - tiempo_inicial_gs

print("Solución con método de Gauss-Seidel:", x_g_s)
print(f"Tiempo del método de Gauss-Seidel: {tiempo_gs:.6f} segundos")

x1 = 3714796191.897235
x2 = 3683328099.849478
x3 = 2621497172.777522
x4 = 2477609279.609012
x5 = 5965110977.079020
x6 = 4576599784.731400
x7 = 4378834929.646802
x8 = 2948214166.555023
x9 = 3118232958.355733
x10 = 3917326773.365271
x11 = 3754031706.700722
x12 = 3969528423.310222
x13 = 4319425675.592587
x14 = 3856580324.604546
x15 = 2095551124.814475
x16 = 1931559529.831292
x17 = 4053560141.404853
x18 = 4129030035.701818
x19 = 3877119798.527790
Solución con método de Gauss-Seidel: (array([3.71479619e+09, 3.68332810e+09, 2.62149717e+09, 2.47760928e+09,
       5.96511098e+09, 4.57659978e+09, 4.37883493e+09, 2.94821417e+09,
       3.11823296e+09, 3.91732677e+09, 3.75403171e+09, 3.96952842e+09,
       4.31942568e+09, 3.85658032e+09, 2.09555112e+09, 1.93155953e+09,
       4.05356014e+09, 4.12903004e+09, 3.87711980e+09]), 2)
Tiempo del método de Gauss-Seidel: 0.002002 segundos

C:\Users\cesar\AppData\Local\Temp\ipykernel_29944\920881888.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[i] = (b[i] - sum_Ax_antes - sum_Ax_desp) / A[i][i]